### ISSUE TITLE
no module "model_prediction_to_feature"

### ISSUE THREAD

**Issue by Jean-Heng-Huang** [jdasam/virtuosoNet#17]
I've use model.run.py on colab.
This is my code:
!python3 model_run.py -mode=test -code=isgn -path=./test_pieces/bps_27_1/ -comp=Beethoven -tempo=90 -vel='50,90'

After fixed the ValueError (I've deleted the variation 'part_names' ) , new Error emerged.
Here shows the Error message: 
=> loading checkpoint 'isgn_best.pth.tar'
device is  0
=> loaded checkpoint 'prime_isgn_best.pth.tar' (epoch 13)
=> loaded checkpoint 'trill_default_best.pth.tar' (epoch 30)
/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py:1949: UserWarning: nn.functional.tanh is deprecated. Use torch.tanh instead.
  warnings.warn("nn.functional.tanh is deprecated. Use torch.tanh instead.")
Traceback (most recent call last):
  File "model_run.py", line 1083, in <module>
    load_file_and_generate_performance(args.testPath)
  File "model_run.py", line 394, in load_file_and_generate_performance
    output_features = xml_matching.model_prediction_to_feature(prediction)
AttributeError: module 'pyScoreParser.xml_matching' has no attribute 'model_prediction_to_feature'

I've found that no function called "model_prediction_to_feature" in xml_matching.py.
Please provide the code of this part, thanks.

**Comment by Jean-Heng-Huang** [comment]
> I've use model.run.py on colab. This is my code: !python3 model_run.py -mode=test -code=isgn -path=./test_pieces/bps_27_1/ -comp=Beethoven -tempo=90 -vel='50,90'
> 
> After fixed the ValueError (I've deleted the variation 'part_names' ) , new Error emerged. Here shows the Error message: => loading checkpoint 'isgn_best.pth.tar' device is 0 => loaded checkpoint 'prime_isgn_best.pth.tar' (epoch 13) => loaded checkpoint 'trill_default_best.pth.tar' (epoch 30) /usr/local/lib/python3.7/dist-packages/torch/nn/functional.py:1949: UserWarning: nn.functional.tanh is deprecated. Use torch.tanh instead. warnings.warn("nn.functional.tanh is deprecated. Use torch.tanh instead.") Traceback (most recent call last): File "model_run.py", line 1083, in load_file_and_generate_performance(args.testPath) File "model_run.py", line 394, in load_file_and_generate_performance output_features = xml_matching.model_prediction_to_feature(prediction) AttributeError: module 'pyScoreParser.xml_matching' has no attribute 'model_prediction_to_feature'
> 
> I've found that no function called "model_prediction_to_feature" in xml_matching.py. Please provide the code of this part, thanks.

I find the function and fixed it!!!!!!
